language: python
sudo: false
env:
  global:
    - PYTHON_VERSION=2.7
  matrix:
    - TEST_ADD_STUDIES=False
    - TEST_ADD_STUDIES=True
before_install:
  - redis-server --version
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # Downloading and setting up ascp for EBI testing
  - wget ftp://ftp.microbio.me/pub/qiita/ascp-install-3.5.4.102989-linux-64-qiita.sh -O ascp-install-3.5.4.102989-linux-64-qiita.sh
  - chmod +x ascp-install-3.5.4.102989-linux-64-qiita.sh
  - ./ascp-install-3.5.4.102989-linux-64-qiita.sh
  - if [ ${TRAVIS_PULL_REQUEST} == "false" ]; then openssl aes-256-cbc -K $encrypted_51ae343d4835_key -iv $encrypted_51ae343d4835_iv -in qiita_core/support_files/config_test_travis.cfg.enc -out qiita_core/support_files/config_test_travis.cfg -d; fi
install:
  # install a few of the dependencies that pip would otherwise try to install
  # when intalling scikit-bio
  - travis_retry conda create --yes -n env_name python=$PYTHON_VERSION pip nose flake8
    pyzmq networkx pyparsing natsort mock future 'pandas>=0.15' 'matplotlib>=1.1.0'
    'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1'
  - source activate env_name
  - pip install sphinx sphinx-bootstrap-theme coveralls ipython[all]==2.4.1
  - travis_retry pip install .
script:
  - export MOI_CONFIG_FP=`pwd`/qiita_core/support_files/config_test.cfg
  - if [ ${TRAVIS_PULL_REQUEST} == "false" ]; then
    export QIITA_CONFIG_FP=`pwd`/qiita_core/support_files/config_test_travis.cfg;
    export MOI_CONFIG_FP=`pwd`/qiita_core/support_files/config_test_travis.cfg;
    fi
  - ipython profile create qiita-general --parallel
  - qiita-env start_cluster qiita-general
  - qiita-env make --no-load-ontologies
  - if [ ${TEST_ADD_STUDIES} == "True" ]; then test_data_studies/commands.sh ; fi
  - if [ ${TEST_ADD_STUDIES} == "False" ]; then qiita-test-install ; fi
  - if [ ${TEST_ADD_STUDIES} == "False" ]; then nosetests --with-doctest --with-coverage; fi
  - if [ ${TEST_ADD_STUDIES} == "False" ]; then flake8 qiita_* setup.py scripts/qiita
    scripts/qiita-env scripts/qiita-test-install ; fi
  - ls -R /home/travis/miniconda3/envs/env_name/lib/python2.7/site-packages/qiita_pet/support_files/doc/
  - qiita pet webserver
addons:
  postgresql: "9.3"
services:
  - redis-server
  - postgresql
after_success:
  - if [ ${TEST_ADD_STUDIES} == "False" ]; then coveralls ; fi
